/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.JOptionPane;
import model.DeliveryPackage;
import model.Customer;
import model.Product;


/**
 *
 * @author nayankarumuri
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Boolean checking=false;
    private DeliveryPackage delPackage;
    
    
    public CreateJPanel() {
        initComponents();
        //this.delPackage=deliveryPackage;
        
        }
    CreateJPanel(DeliveryPackage deliveryPackage){
        initComponents();
        this.delPackage=deliveryPackage;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        saveProductbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, -1));
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 120, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, -1));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, -1));

        custName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custName1FocusLost(evt);
            }
        });
        add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 90, -1));

        jLabel1.setText("Package Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setText("Product Id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setText("Product Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel5.setText("Product Price");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel6.setText("Id");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        Savebtn.setText("SAVE");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 40));

        saveProductbtn.setText("Save Product");
        saveProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductbtnActionPerformed(evt);
            }
        });
        add(saveProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        
        String id=packageId.getText();
        String weight=packageWt.getText();
        //String productId=productId1.getText();
        //String productName1=productName.getText();
        //String productPrice1=productPrice.getText();
        String customerId=custId.getText();
        String customerName=custName1.getText();
        
        
        
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        /*  Product product=this.delPackage.getProduct();
        product.setProductId(Integer.valueOf(productId));
        product.setProductName(productName1);
        product.setPrice((Double.valueOf(productPrice1)));    */
        
        if (checking){
            JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE DETAILS TO PROCEED FURTHER!");
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Created!");
            
        }
        
    
        
        
    }//GEN-LAST:event_SavebtnActionPerformed

    private void saveProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductbtnActionPerformed
        // TODO add your handling code here:
        String productId=productId1.getText();
        String productName=productName1.getText();
        String productPrice1=productPrice.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice1));
       
        JOptionPane.showMessageDialog(null, "Added Product");
        
                
        
    }//GEN-LAST:event_saveProductbtnActionPerformed

    private void custName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custName1FocusLost
        // TODO add your handling code here:
        
        System.out.println(custName1.getText() + " -- the customer name");
        String name = custName1.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.checking = true;
        } else {
            this.checking = false;
        }
    }//GEN-LAST:event_custName1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebtn;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton saveProductbtn;
    // End of variables declaration//GEN-END:variables
}
