/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.JOptionPane;
import model.Customer;
import model.DeliveryPackage;
import model.Product;


/**
 *
 * @author nayankarumuri
 */
public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    private DeliveryPackage delPackage;
    private Product productViewed;
    
    public EditJPanel() {
        initComponents();
    }
    
    EditJPanel(DeliveryPackage deliveryPackage){
        initComponents();
        this.delPackage = deliveryPackage;

        displayProductList();
        
        displayPackageDetails();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prodUpdatebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        prodComboBox = new javax.swing.JComboBox();
        showBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, -1));
        jPanel1.add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));
        jPanel1.add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 150, -1));
        jPanel1.add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 150, -1));
        jPanel1.add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, -1));
        jPanel1.add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, -1));
        jPanel1.add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 90, -1));

        jLabel1.setText("Package Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("weight");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setText("Product Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        jLabel4.setText("Product Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel5.setText("Product Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel6.setText("Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        prodUpdatebtn.setText("Update Product");
        prodUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodUpdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(prodUpdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, 40));

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jPanel1.add(prodComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, -1));

        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        jPanel1.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        String id = packageId.getText();
        String weight = packageWt.getText();
        String customerId = custId.getText();
        String customername = custName1.getText();
        
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customername);
        
    }//GEN-LAST:event_UpdatebtnActionPerformed

       
    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        
        productId1.setEnabled(false);
        
        int pid = (int) prodComboBox.getSelectedItem();

        // find the product in the arraylsit
        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) {
            productId1.setText(String.valueOf(pid));
            productName1.setText(prod.getProductName());
            productPrice.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }

    }                                       

    public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            prodComboBox.addItem(p.getProductId());
        }

    }

    public void displayPackageDetails() {
        packageId.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWt.setText(String.valueOf(this.delPackage.getPackageWeight()));

        Customer customer = this.delPackage.getCustomer();
        custId.setText(String.valueOf(customer.getCustomerId()));
        custName1.setText(customer.getFullName());

    
    }//GEN-LAST:event_showBtnActionPerformed

    private void prodUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodUpdatebtnActionPerformed
    this.productViewed.setProductName(productName1.getText());
        this.productViewed.setPrice(Double.valueOf(productPrice.getText()));
        
    }//GEN-LAST:event_prodUpdatebtnActionPerformed
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatebtn;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JComboBox prodComboBox;
    private javax.swing.JButton prodUpdatebtn;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton showBtn;
    // End of variables declaration//GEN-END:variables
}
