/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.DeliveryPackage;
import model.Customer;
import model.Product;

/**
 *
 * @author nayankarumuri
 */
public class ViewJPanel extends javax.swing.JPanel {
    private DeliveryPackage delPackage;
    private Product productViewed;

    /**
     * Creates new form ViewJPanel
     */
    
    public ViewJPanel() {
        initComponents();
    }
    
    ViewJPanel(DeliveryPackage deliveryPackage){
        initComponents();
        this.delPackage=deliveryPackage;
        
        display();
        displayProductList();
    }

    public void display(){
        packageId.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWt.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer customer = this.delPackage.getCustomer();
        custId.setText(String.valueOf(customer.getCustomerId()));
        custName1.setText(customer.getFullName());
        
    
}
    
    public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            showComboBox.addItem(p.getProductId());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productId1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showComboBox = new javax.swing.JComboBox();
        showProduct = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, -1));
        jPanel1.add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));
        jPanel1.add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, -1));
        jPanel1.add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 80, -1));
        jPanel1.add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, -1));
        jPanel1.add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, -1));

        jLabel1.setText("Package Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("weight");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setText("Product Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel4.setText("Product Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel5.setText("Product Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel6.setText("Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jPanel1.add(showComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, -1));

        showProduct.setText("show prod list details");
        showProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductActionPerformed(evt);
            }
        });
        jPanel1.add(showProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProductActionPerformed
        // TODO add your handling code here:
        productId1.setEnabled(false);
        
        int pid=(int) showComboBox.getSelectedItem();
        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) {
            productId1.setText(String.valueOf(pid));
            productName1.setText(prod.getProductName());
            productPrice1.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_showProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    private javax.swing.JComboBox showComboBox;
    private javax.swing.JButton showProduct;
    // End of variables declaration//GEN-END:variables
}
