/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.MedicineCatalog;
import Model.Medicine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nayankarumuri
 */
public class CatalogJpanel extends javax.swing.JPanel {
    private Application application;

    /**
     * Creates new form CatalogJpanel
     */
    
    DefaultTableModel medTableModel;
    CatalogJpanel(Application application) {
        initComponents();
        
        this.application=application;
        this.medTableModel= (DefaultTableModel) medicineCatalogTbl.getModel();
        
        displayMedicineCatalog();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtn = new javax.swing.JButton();
        fieldName = new javax.swing.JTextField();
        fieldDosage = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalogTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, -1));

        fieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNameFocusLost(evt);
            }
        });
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 70, -1));
        add(fieldDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        medicineCatalogTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineCatalogTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 170));

        jLabel1.setText("name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setText("Dosage");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        
        String name=fieldName.getText();
        String dosage=fieldDosage.getText();
        
        MedicineCatalog catalog = this.application.getCatalog();
        
        catalog.createMedicine(name, Double.valueOf(dosage));
        displayMedicineCatalog();
    }//GEN-LAST:event_AddBtnActionPerformed

    private void fieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameFocusLost
        // TODO add your handling code here:
        String name=fieldName.getText();
        Boolean isUnique=this.application.getCatalog().checkIfMedicineUnique(name);
        
        if(isUnique) {
            
        }else {
            fieldName.setText("");
            JOptionPane.showMessageDialog(null, "Medicine already exists");
        }
    }//GEN-LAST:event_fieldNameFocusLost

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = medicineCatalogTbl.getSelectedRow();
        
        if(selectedRow >= 0){
            
            Medicine med=(Medicine) medicineCatalogTbl.getValueAt(selectedRow, 0);
            this.application.getCatalog().removeMedicine(med.getMedicineName());
            
            displayMedicineCatalog();
        } else {
            JOptionPane.showMessageDialog(null, "select row");
            
            
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
 
    public void displayMedicineCatalog(){
        
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        
        if(medicines.size()>0) {
            medTableModel.setRowCount(0);
            
            for(Medicine med: medicines){
                
                Object row[]=new Object[2];
                row[0]=med;
                row[1]=med.getDosage();
                
                medTableModel.addRow(row);
            } 
                
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fieldDosage;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalogTbl;
    // End of variables declaration//GEN-END:variables
}
