/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author nayankarumuri
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    private Application application;

    /**
     * Creates new form CreateJPanel
     */
    
    CreateJPanel(Application application) {
        initComponents();
        
        this.application=application;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTemp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldBP = new javax.swing.JTextField();
        addObsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        add(fieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 80, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 20, -1));
        add(fieldTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, -1));

        jLabel3.setText("Temp");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("BP");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, -1));
        add(fieldBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 70, -1));

        addObsBtn.setText("Add Observation");
        addObsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObsBtnActionPerformed(evt);
            }
        });
        add(addObsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObsBtnActionPerformed
        // TODO add your handling code here:
        
        VitalSignHistory history=this.application.getHistory();
        
        String id=fieldId.getText();
        String temp=fieldTemp.getText();
        String bloodTemp=fieldBP.getText();
        
        //converting casting
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(temp), Double.valueOf(bloodTemp));
        
        JOptionPane.showMessageDialog(null, "Observation added successfully");
    }//GEN-LAST:event_addObsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObsBtn;
    private javax.swing.JTextField fieldBP;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
