/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author nayankarumuri
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {
    private Application application;

    /**
     * Creates new form MedicineAssign
     */
    

    MedicineAssignJPanel(Application application) {
        initComponents();
        
        this.application=application;
        populateDropdowns();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineBox = new javax.swing.JComboBox();
        ObservationBox = new javax.swing.JComboBox();
        AssignBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));

        ObservationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ObservationBoxItemStateChanged(evt);
            }
        });
        add(ObservationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 110, -1));

        AssignBtn.setText("Assign");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });
        add(AssignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:
        
        Observation o= (Observation)  ObservationBox.getSelectedItem();
        Medicine m= (Medicine) medicineBox.getSelectedItem();
        
        o.setMedication(m);
        
    }//GEN-LAST:event_AssignBtnActionPerformed

    private void ObservationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ObservationBoxItemStateChanged
        // TODO add your handling code here:
        Observation o=(Observation) ObservationBox.getSelectedItem();
        if(o.getMedication()!= null) {
        
        jLabel1.setText(o.getMedication().getMedicineName());
             
        }
        
    }//GEN-LAST:event_ObservationBoxItemStateChanged

    
    
    public void populateDropdowns() {
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o : observations){
            ObservationBox.addItem(o);
        }
        
        for(Medicine med: medicines){
            medicineBox.addItem(med);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JComboBox ObservationBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox medicineBox;
    // End of variables declaration//GEN-END:variables
}
